<!DOCTYPE html>
<html>
<head>
	<?php echo Tag::css('estilos') ?>
	<title>Titulos</title>
	

</head>
<body>
	<section align="center">
		<?php View::content(); ?>
<br>
<?php echo Form::open(); // por defecto llama a la misma url ?>
 
<form>
<h3 align="center">Agregar Organizador</h3>

<table cellspacing="12px"><tr>
			<tr>
		<td>
			 <label>Pago</label>
		</td>
		<td>
        	 <?php echo Form::text('pagodetalle.pago_id') ?>
		</td>
	</tr>

	<tr>
		<td>
			 <label>Catalogo</label>
		</td>
		<td>
        	 <?php echo Form::text('pagodetalle.catalogo_id') ?>
		</td>
	</tr>

	<tr>
		<td>
			 <label>Importe</label>
		</td>
		<td>
        	 <?php echo Form::text('pagodetalle.importe') ?>
		</td>
	</tr>

	<tr>
		<th colspan="2">
			   <?php echo Form::hidden('evento.id') ?>
        <?php echo Form::submit('Actualizar') ?>
		</th>
	</tr>
        


</table>

<?php echo Html::linkAction("", 'Lista') ?>
</form>
   
<?php echo Form::close() ?>
</section>
</body>
</html>
