<?php View::content(); ?>
<h3>Editar Usuario</h3>
<?php echo Form::open(); // por defecto llama a la misma url ?>
 
       <label>Nombre
        <?php echo Form::text('usuarios.Nombre') ?></label>

        <label>Apellido
        <?php echo Form::text('usuarios.Apellido') ?></label>
        
        <label>Edad
        <?php echo Form::text('usuarios.Edad') ?></label>
 
        <?php echo Form::hidden('usuarios.id') ?>
        <?php echo Form::submit('Actualizar') ?>
 
<?php echo Form::close() ?>