<!DOCTYPE html>
<html lang="es">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>KumbiaPHP web &amp; app Framework</title>
	<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/style.css" />

	<link href="/Kumbia/default/public/libs/bootstrap/css/bootstrap.min.css" rel="style">
	<script src="/Kumbia/default/public/libs/bootstrap/js/bootstrap.min"></script>
</head>
<body>
	<?php View::content(); ?>
</body>
</html>
