<!DOCTYPE html>
<html>
<head>

 </head>
<body>
	
	<section align="center">
 <?php echo Tag::css('estilos') ?>
<?php View::content(); ?>
<br>
<?php echo Form::open(); // por defecto llama a la misma url ?>
<form>
<h3 align="center">Editar Organizador</h3>
<br>
<table cellspacing="12px"><tr>
		<td>
			 <label>Catalogo</label>
		</td>
		<td>
        	 <?php echo Form::text('horario.catalogo_id') ?>
		</td>
	</tr>

	<tr>
		<td>
			 <label>Ponente</label>
		</td>
		<td>
        	 <?php echo Form::text('horario.ponente_id') ?>
		</td>
	</tr>

	<tr>
		<th colspan="2">
			 <?php echo Form::hidden('evento.id') ?>
        	 <?php echo Form::submit('Actualizar') ?>
		</th>
	</tr>
        


</table>

<?php echo Html::linkAction("", 'Lista') ?>
</form>
   
<?php echo Form::close() ?>
</section>
</body>
</html>
