<!DOCTYPE html>
<html>
<head>
    <?php echo Tag::css('estilos') ?>
    <title>Titulos</title>
<link rel="stylesheet" href="/Kumbia/default/public/css/estilos3.css">
</head>
<body>
<table width="200" border="0" align="center">
  <tr>
    <td><img src="/Kumbia/default/public/img/itvologo.jpg" width="1300" height="350" alt="ITVO"></td>
  </tr>
  <tr>
    <td>
        <nav class="navegacion">
            <ul class="menu" align="center">
      <li><a href="/kumbia/">Inicio</a>  
      <li><a href="#">Ponente</a>
      <ul class="submenu">
                        <li><a href="/kumbia/ponente/create">Crear</a></li>
                        <li><a href="/kumbia/ponente">Ver</a></li>
          </ul>
        <li><a href="#">Participante</a>
        <ul class="submenu">
                        <li><a href="/kumbia/participante/create">Crear</a></li>
                        <li><a href="/kumbia/participante">Ver</a></li>
          </ul>
          </li>
                <li><a href="#">Evento</a>
                    <ul class="submenu">
                        <li><a href="/kumbia/evento/create">Crear</a></li>
                        <li><a href="/kumbia/evento">Ver</a></li>
                    </ul>
                </li>
        <li><a href="#">Organizador</a>
          <ul class="submenu">
            <li><a href="/kumbia/organizador/create">Crear</a></li>
            <li><a href="/kumbia/organizador">Ver</a></li>
          </ul>
                <li><a href="#">Actividad</a>
          <ul class="submenu">
            <li><a href="/kumbia/actividad/create">Crear</a></li>
            <li><a href="/kumbia/actividad">Ver</a></li>
          </ul>
        <li><a href="#">Catalogo</a>
          <ul class="submenu">
            <li><a href="/kumbia/catalogo/create">Crear</a></li>
            <li><a href="/kumbia/catalogo">Ver</a></li>
          </ul>
        <li><a href="#">Pago</a>
          <ul class="submenu">
            <li><a href="/kumbia/pago/create">Crear</a></li>
            <li><a href="/kumbia/pago">Ver</a></li>
          </ul>
        <li><a href="#">Detalle Pago</a>
        <ul class="submenu">
            <li><a href="/kumbia/pagodetalle/create">Crear</a></li>
            <li><a href="/kumbia/pagodetalle">Ver</a></li>
          </ul>
        <li><a href="#">Horarios</a>
        <ul class="submenu">
            <li><a href="/kumbia/horario/create">Crear</a></li>
            <li><a href="/kumbia/horario">Ver</a></li>
          </ul>
        <li><a href="#">Detalles Horario</a>
        <ul class="submenu">
            <li><a href="/kumbia/horariodetalle/create">Crear</a></li>
            <li><a href="/kumbia/horariodetalle">Ver</a></li>
          </ul>
        <li><a href="#">Horario Participante</a>
          <ul class="submenu">
            <li><a href="/kumbia/participantehorario/create">Crear</a></li>
            <li><a href="/kumbia/participantehorario">Ver</a></li>
          </ul>
        <li><a href="#">Categoria</a>
          <ul class="submenu">
            <li><a href="/kumbia/categoria/create">Crear</a></li>
            <li><a href="/kumbia/categoria">Ver</a></li>
          </ul>

            </ul>
        </nav>
    </td>
  </tr>
  
</table>
 
    <section align="center">
            <br>
    <?php View::content(); ?>
    <h3 align="center">Evento</h3>
   <center>
    <table >
        <tr>
            <th class="tab"><i>ID</i></th>
            <th class="tab"><i>Titulo</i></th>
            <th class="tab"><i>Descripcion</i></th>
            <th class="tab"><i>Fecha de Inicio</i></th>
            <th class="tab"><i>Fecha de Finalizacion</i></th>
            <th class="tab"><i>Observaciones</i></th>
            <th class="tab"><i>Logotipo</i></th>
            <th class="tab"><i>Eslogan</i></th>
            <th class="tab"><i>Lugar</i></th>
            <th class="tab"><i>Categoria</i></th>
            <th class="tab"><i>Inicio de Registro</i></th>
            <th class="tab"><i>Cierre de Registro</i></th>
            <th class="tab"><i>Organizador</i></th>
            <th class="tab"><i>Opciones</i></th>

      
        </tr>
        <?php foreach ($listEvento->items as $evento):?>
            <tr>
            <td class="tab"><?php echo $evento->id?></td>
            <td class="tab"><?php echo $evento->titulo?></td>
            <td class="tab"><?php echo $evento->descripcion?></td>
            <td class="tab"><?php echo $evento->fechainicio?></td>
            <td class="tab"><?php echo $evento->fechafin?></td>
            <td class="tab"><?php echo $evento->observaciones?></td>
            <td class="tab"><?php echo $evento->logotipo?></td>
            <td class="tab"><?php echo $evento->eslogan?></td>
            <td class="tab"><?php echo $evento->lugar?></td>
            <td class="tab"><?php echo $evento->descripcionc?></td>
            <td class="tab"><?php echo $evento->inicioregistro?></td>
            <td class="tab"><?php echo $evento->cierreregistro?></td>
            <td class="tab"><?php echo $evento->organizador_id?></td>
            <td class="tab" align="center">
                
                 <?php echo Html::linkAction("edit/$evento->id/", 'Editar') ?>
                 <?php echo Js::linkAction("del/$evento->id/", 'Borrar') ?>
            </td>
            </tr>
         <?php endforeach;?> 
    </table>  

    <br/>
    <p class="links"><?php if ($listEvento->prev) echo Html::linkAction("index/$listEvento->prev/", '<< Anterior |'); ?></p>
    <p class="links"><?php if ($listEvento->next) echo Html::linkAction("index/$listEvento->next/", 'Próximo >>'); ?></p>
    <br/>
    <a href="/kumbia/evento/create/"><input type="button" value="Registrar Nuevo"></a>
    

        </section>
</body>
</html>