<!DOCTYPE html>
<html>
<head>
    <?php echo Tag::css('estilos') ?>
    <title>Titulos</title>
<link rel="stylesheet" href="/Kumbia/default/public/css/estilos3.css">
</head>
<body>
<table width="200" border="0" align="center">
  <tr>
    <td><img src="/Kumbia/default/public/img/vaner2.png" width="1300" height="350" alt="ITVO"></td>
  </tr>
  <tr>
    <td>
        <nav class="navegacion">
            <ul class="menu" align="center">
      <li><a href="/kumbia/alumno/inicio/">Inicio participantes</a>  
      <li><a href="#">cursos</a>
      <ul class="submenu">
            <li><a href="/kumbia/catalogo">tomar</a></li>
            </ul>
        <li><a href="#">Catalogo</a>
          <ul class="submenu">
            <li><a href="#">Ver</a></li>
          </ul>
         <li><a href="#">Horarios</a>
        <ul class="submenu">
            <li><a href="#">Ver</a></li>
          </ul>
          <li><a href="#">Horario Participante</a>
          <ul class="submenu">
          <li><a href="#">Ver</a></li>
          </ul>
       

            </ul>
        </nav>
    </td>
  </tr>
  
</table>
 
    <section align="center">
            <br>
    <?php View::content(); ?>
    <h3 align="center">Catalogo</h3>
    <center>
    <table>
        <tr>
            <th class="tab"><i>ID</i></th>
            <th class="tab"><i>Titulo</i></th>
            <th class="tab"><i>Actividad</i></th>
            <th class="tab"><i>Evento</i></th>
            <th class="tab"><i>Costo</i></th>
            <th class="tab"><i>Horas</i></th>
            <th class="tab"><i>Cupo limite</i></th>
            <th class="tab"><i>Opciones</i></th>

      
        </tr>
        <?php foreach ($listCatalogo->items as $catalogo):?>
            <tr>
            <td class="tab"><?php echo $catalogo->id?></td>
            <td class="tab"><?php echo $catalogo->titulo?></td>
            <td class="tab"><?php echo $catalogo->descripcion?></td>
            <td class="tab"><?php echo $catalogo->titulos?></td>
            <td class="tab"><?php echo $catalogo->costo?></td>
            <td class="tab"><?php echo $catalogo->totalhoras?></td>
            <td class="tab"><?php echo $catalogo->cupolimite?></td>
            <td class="tab" align="center">
                
                 <?php echo Html::linkAction("edit/$catalogo->id/", 'Editar') ?>
                 <?php echo Js::linkAction("del/$catalogo->id/", 'Borrar') ?>
            </td>
            </tr>
         <?php endforeach;?> 
    </table>  

    <br/>
    <p class="links"><?php if ($listCatalogo->prev) echo Html::linkAction("index/$listCatalogo->prev/", '<< Anterior |'); ?></p>
    <p class="links"><?php if ($listCatalogo->next) echo Html::linkAction("index/$listCatalogo->next/", 'Próximo >>'); ?></p>
    <br/>
    
    </center>
        </section>
</body>
</html>