<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=UTF-8 >
  <title> ITVO </title>
  <link rel="stylesheet" href="/Kumbia/default/public/css/estilos3.css">
</head>
<body>
<table width="200" border="0" align="center">
  <tr>
    <td><img src="/Kumbia/default/public/img/vaner2.png" width="1300" height="350" alt="ITVO"></td>
  </tr>
  <tr>
    <td>
		<nav class="navegacion">
			<ul class="menu" align="center">
      <li><a href="/kumbia/alumno/inicio/">Inicio particípante</a>  
      <li><a href="#">Cursos</a>
      <ul class="submenu">
						<li><a href="/kumbia/participante/create/">tomar</a></li>
						</ul>
       
        <li><a href="#">Catalogo</a>
          <ul class="submenu">
            <li><a href="/kumbia/catalogo">Ver</a></li>
          </ul>
       
        <li><a href="#">Horarios</a>
        <ul class="submenu">
            <li><a href="/kumbia/horario">Ver</a></li>
          </ul>
        
        <li><a href="">Horario Participante</a>
          <ul class="submenu">
          <li><a href="/kumbia/participantehorario">Ver</a></li>
          </ul>
       

			</ul>
		</nav>
	</td>
  </tr>
  <tr>
    <td height="369">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>

</body>
</html>
